#include <assert.h>
#include <cstring>
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "stack.h"
#include "stringsort.h"
#include "enum_commands.h"
#include "cpu.h"
#include "asm.h"
#include <windows.h>
#define _DEBUG
